// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT21wRSHooSHnLWPDmYc0doh1OkIyLx38',
    appId: '1:491265011493:web:96884be7f9a7eae07474cc',
    messagingSenderId: '491265011493',
    projectId: 'appointment-37b59',
    authDomain: 'appointment-37b59.firebaseapp.com',
    storageBucket: 'appointment-37b59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlvSVKyJoRZHVYjGKWBk71IuLd78psPnQ',
    appId: '1:491265011493:android:2d59d7a1cd2868487474cc',
    messagingSenderId: '491265011493',
    projectId: 'appointment-37b59',
    storageBucket: 'appointment-37b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFGbOGeaBHPTb2tgiwchLaK_gt4y4QfI',
    appId: '1:491265011493:ios:ee9509137e4d058f7474cc',
    messagingSenderId: '491265011493',
    projectId: 'appointment-37b59',
    storageBucket: 'appointment-37b59.firebasestorage.app',
    iosBundleId: 'com.example.userProfileManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFGbOGeaBHPTb2tgiwchLaK_gt4y4QfI',
    appId: '1:491265011493:ios:ee9509137e4d058f7474cc',
    messagingSenderId: '491265011493',
    projectId: 'appointment-37b59',
    storageBucket: 'appointment-37b59.firebasestorage.app',
    iosBundleId: 'com.example.userProfileManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT21wRSHooSHnLWPDmYc0doh1OkIyLx38',
    appId: '1:491265011493:web:f33361c629aec1547474cc',
    messagingSenderId: '491265011493',
    projectId: 'appointment-37b59',
    authDomain: 'appointment-37b59.firebaseapp.com',
    storageBucket: 'appointment-37b59.firebasestorage.app',
  );
}
